package com.example.accessdata.controller;

import com.example.accessdata.dao.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

/**
 * @ClassName: MainController
 * @Author: hongchenjie-(Evins)
 * @Data: 2026/7/15 19:15
 * @Version: 1.0.0
 * @Description: TODO
 */

@RestController
public class MainController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @GetMapping(path="/get") // Map ONLY POST Requests
    public String getUser () {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        System.out.println("maincontroller get method...."+userRepository.findById(1));
        return userRepository.findById(1).toString();
    }
}
